#!/bin/sh

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket

case "$1" in
	start)
		echo "Starting ${NAME}"
		start-stop-daemon -S -q -n ${NAME} -x ${DAEMON} -- -d
		;;
	stop)
		echo "Stopping ${NAME}"
		start-stop-daemon -K -q -s TERM -n ${NAME}
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
